// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('carStore.store.CarChartJson', {
    extend: 'Ext.data.Store',
    requires: ['carStore.model.CarChartModel'],
    model: 'carStore.model.CarChartModel',
    proxy: {
      type: 'ajax',
      reader: {
        type: 'json'
      }
    }
  });

}).call(this);
