// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('carStore.store.CarDataJson', {
    extend: 'Ext.data.Store',
    mixins: ['Deft.mixin.Injectable'],
    requires: ['carStore.model.CarDataModel'],
    inject: ['appConfig'],
    constructor: function(cfg) {
      var me;
      me = this;
      cfg = cfg || {};
      return me.callParent([
        Ext.apply({
          autoLoad: true,
          model: 'carStore.model.CarDataModel',
          proxy: {
            type: 'ajax',
            url: this.appConfig.getEndpoint('cars').url,
            reader: {
              type: 'json',
              root: this.appConfig.getEndpoint('cars').root
            }
          }
        }, cfg)
      ]);
    }
  });

}).call(this);
