// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('carStore.view.Viewport', {
    extend: 'carStore.view.CarListings',
    renderTo: Ext.getBody(),
    requires: ['carStore.view.CarListings']
  });

}).call(this);
