// Generated by CoffeeScript 1.3.1
(function() {

  Ext.Loader.setConfig({
    enabled: true
  });

  Ext.application({
    autoCreateViewport: true,
    name: "carStore"
  });

  Ext.onReady(function() {
    return Deft.Injector.configure({
      appConfig: {
        className: "carStore.appconfig.AppConfig",
        parameters: [
          {
            environment: "MOCK_DATA_ENV"
          }
        ]
      },
      carChartJson: "carStore.store.CarChartJson",
      carDataJson: "carStore.store.CarDataJson"
    });
  });

}).call(this);
