// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('carStore.controller.MyViewController', {
    extend: 'Deft.mvc.ViewController',
    mixins: ['Deft.mixin.Injectable'],
    inject: ['carChartJson', 'carDataJson'],
    control: {
      carGrid: {
        selectionchange: 'onCarGridSelectionChange'
      },
      carDetail: true,
      carChartPanel: true
    },
    config: {
      carChartJson: null,
      carDataJson: null
    },
    init: function() {
      return this.callParent(arguments);
    },
    onCarGridSelectionChange: function(selectionModel, selections) {
      var carDataModel;
      carDataModel = selections[0];
      this.getCarDetail().update(carDataModel.getData());
      return this.getCarChartJson().loadData(carDataModel.getData().quality);
    }
  });

}).call(this);
